#' Henter data registrert for Degenerativ Rygg
#'
#' Henter data for Degenerativ Rygg fra "staging" (?)
#'
#' @inheritParams FigAndeler
#'
#' @return RegData data frame
#' @export
#'
RyggRegDataSQL <- function() {
      
#RyggRegDataSQL <- function(datoFra = '2007-01-01', datoTil = '2099-01-01') 
#Dette blir feil siden Rygg i staging har datoformat dd.mm.yyyy

  registryName <- "nkr"
  dbType <- "mssql"

  
#  query = 'select * from Uttrekk_Rapport'
  
  query <- paste0('SELECT
	Andrestudier,
	Alder,
	AnnetMorsm,
	AntBarn,
	Antibiotika,
	AntNivOpr,
	Arbstatus12mnd,
	Arbstatus3mnd,
	ArbstatusPre,
	ASA,
	AvdID,
	AvdNavn,
	AvdReshID,
	BMI,
	Dagkirurgi,
	EQ5D12mnd,
	EQ5D3mnd,
	EQ5DPre,
	Eqangst12mnd,
	Eqangst3mnd,
	EqangstPre,
	Eqgange12mnd,
	Eqgange3mnd,
	EqgangePre,
	Eqperst12mnd,
	Eqperst3mnd,
	EqperstPre,
	Eqsmerte12mnd,
	Eqsmerte3mnd,
	EqsmertePre,
	Eqvanlgj12mnd,
	Eqvanlgj3mnd,
	EqvanlgjPre,
	ErstatningPre,
	Fornoyd12mnd,
	Fornoyd3mnd,
	FusjonKirAlif,
	FusjonKirAlifBen,
	FusjonKirAlifBur,
	FusjonKirPlf,
	FusjonKirPlfIntr,
	FusjonKirPlif,
	FusjonKirTlif,
	FusjonSpes,
	Helsetilst12mnd,
	Helsetilst3mnd,
	HelsetilstPre,
	HFID,
	HFNavn,
	HFReshID,
	HovedInngrep,
	HovedInngreptxt,
	Hoyde,
	Inngrep,
	Inngreptxt,
	Kjonn,
	KnivtidTot,
	Kommunenr,
	Kp3Mnd,
	KpBlod3Mnd,
	KpDVT3Mnd,
	KpInf3Mnd,
	KpInfDyp12Mnd,
	KpInfDyp3Mnd,
	KpInfOverfla3Mnd,
	KpLE3Mnd,
	KpLungebet3Mnd,
	KpMiktProb3Mnd,
	KpSarinfUspesType3Mnd,
	KpUVI3Mnd,
	Liggedogn,
	Morsmal,
	Nytte12mnd,
	Nytte3mnd,
	OpAar,
	OpAndreSkiveprotese,
	OpAndreSpes,
	OpDato,
	OpDeFasett,
	OpDeFasettUniBi,
	OpDeUlamin,
	OpDeUlaminTilgang,
	OpIndCauda,
	OpIndParese,
	OpIndPareseGrad,
	OpIndSme,
	OpIndSmeType,
	OpKat,
	OpL23,
	OpL34,
	OpL45,
	OpL5S1,
	OpLaminektomi,
	OpMikro,
	OpProlap,
	OpTilgang,
	OswTot12mnd,
	OswTot3mnd,
	OswTotPre,
	PeropKomp,
	PeropKompAnafy,
	PeropKompAnnet,
	PeropKompDura,
	PeropKompFeilnivSide,
	PeropKompFeilplassImp,
	PeropKompKardio,
	PeropKompNerve,
	PeropKompResp,
	PeropKompTransfuBlodning,
	PID,
	ProsKode1,
	ProsKode2,
	Region,
	Reop90d,
	RfAnnet,
	RfAnnetspes,
	RfDegen,
	RfDegskol,
	RfForamino,
	RfLateral,
	RfNormal,
	RfPseudom,
	RfSentr,
	RfSkive,
	RfSpondtypeDegen,
	RfSpondtypeIsmisk,
	RfSynovpre,
	Roker,
	RvCt,
	RvDiscogr,
	RvDpregblok,
	RvFunksjo,
	RvMr,
	RvRadigr,
	RvRtgLscol,
	Saardren,
	SivilStatus,
	SkjemaIDIa,
	SkjemaIDIIa,
	SmBe12mnd,
	SmBe3mnd,
	SmBePre,
	SmHypp12mnd,
	SmHypp3mnd,
	SmHyppPre,
	SmRy12mnd,
	SmRy3mnd,
	SmRyPre,
	SmSti12mnd,
	SmSti3mnd,
	SmStiPre,
	Sykd,
	SykdAndreRelevanteSykdBechtrew,
	SykdAnnenendokrin,
	SykdAnnenreumatisk,
	SykdAnnet,
	SykdCerebrovaskular,
	SykdDepresjonAngst,
	SykdHjertekar,
	SykdHoftekneartose,
	SykdHypertensjon,
	SykdKreft,
	SykdKroniskLunge,
	SykdKroniskNevrologisk,
	SykdKroniskSmerterMuskelSkjelettsyst,
	SykdOsteoporose,
	SykDprebetesMellitus,
	SykdReumatoidartritt,
	SykdVaskulærClaudicatio,
	Sykehustype,
	SykemeldVarighPre,
	SymptVarighRyggHof,
	SympVarighUtstr,
	TideOp12mnd,
	TideOp3mnd,
	TidlOpr,
	TidlOprAntall,
	TypeBen,
	TypeBenBensub,
	UforetrygdPre,
	Utd,
	Utfylt12Mnd,
	Utfylt3Mnd,
	Vekt
FROM Uttrekk_Rapport
#                  WHERE OpDato >= \'', datoFra, '\' AND OpDato <= \'', datoTil, '\'')

RegData <- rapbase::LoadRegData(registryName, query, dbType)


return(RegData)
}


